### ISSUE TITLE
Feature Request: move scanning area via bot

### ISSUE THREAD

**Issue by PhDeez** [eugenio412/PogomBOT#22] opened 2016-08-20 02:26 UTC
I saw this request over in pogom and feel it would be a pretty great thing to offer via pogomBOT.  Move the scanning area via the bot.

(https://github.com/favll/pogom/issues/328)

I would envision something like send location and then a /scanradius 1200.

**Comment by Unknown66** [comment] 2016-08-20 09:06
Duplicate of #1.

**Comment by PhDeez** [comment] 2016-08-20 13:36
My bad, I didn't look in closed requests.  I believe additional work needs to occur on the pogom side, but if we can get the handlers worked out on the bot side it might motivate the pogom side to complete their development.  I would think webhooks would be the easiest way, but honestly I don't know.

Additional thought: We would also need to "delete" previously placed pins/locations since if we were just adding locations we would just extend the scanning area (and therefore increase the total scan time).  I'm thinking if a new lat/lon is received, reset all scanning areas..

**Closed as completed** 2016-08-20 18:58 UTC
Labels: duplicate
